from typing import List

from pydantic import BaseModel, Field


class RequestModel(BaseModel):
    request: str = Field(
        ...,
        description="Natural language request from the user."
    )


class TaskModel(BaseModel):
    step: int = Field(..., description="Task sequence number")
    description: str = Field(..., description="Description of the task")


class PlannerModel(BaseModel):
    document_type: str = Field(
        ...,
        description="Type of business document to generate"
    )

    goal: str = Field(
        ...,
        description="Overall objective of the request"
    )

    assumptions: List[str] = Field(
        default_factory=list,
        description="Assumptions made by the agent"
    )

    tasks: List[TaskModel] = Field(
        default_factory=list,
        description="Execution plan generated by the planner"
    )


class ResponseModel(BaseModel):
    status: str = Field(
        ...,
        description="Execution status"
    )

    message: str = Field(
        ...,
        description="Success or failure message"
    )

    document_name: str = Field(
        ...,
        description="Generated Word document name"
    )

    tasks: List[TaskModel] = Field(
        default_factory=list,
        description="Executed task list"
    )